# Declare properties here
display.visualizations.custom.retail-map-viz.map_viz.mapImage = <string>
display.visualizations.custom.retail-map-viz.map_viz.mapHeight = <int>
display.visualizations.custom.retail-map-viz.map_viz.mapWidth = <int>
display.visualizations.custom.retail-map-viz.map_viz.allPopups = <string>
display.visualizations.custom.retail-map-viz.map_viz.multiplePopups = <string> 
display.visualizations.custom.retail-map-viz.map_viz.scrollWheelZoom = <string>
display.visualizations.custom.retail-map-viz.map_viz.fullScreen = <string>
display.visualizations.custom.retail-map-viz.map_viz.drilldown = <string>
display.visualizations.custom.retail-map-viz.map_viz.defaultHeight = <int>
display.visualizations.custom.retail-map-viz.map_viz.mapCenterZoom = <int>
display.visualizations.custom.retail-map-viz.map_viz.mapCenterX = <int>
display.visualizations.custom.retail-map-viz.map_viz.mapCenterY = <int>
display.visualizations.custom.retail-map-viz.map_viz.minZoom = <int>
display.visualizations.custom.retail-map-viz.map_viz.maxZoom = <int>
display.visualizations.custom.retail-map-viz.map_viz.kmlOverlay = <string>
display.visualizations.custom.retail-map-viz.map_viz.showPath = <string> 
display.visualizations.custom.retail-map-viz.map_viz.focusClicked= <string>
display.visualizations.custom.retail-map-viz.map_viz.unfocusedOpacity = <int> 
